// <auto-generated />
using System;
using Assessment_JulianFelipeForeroVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_JulianFelipeForeroVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115154748_CreateTableUser")]
    partial class CreateTableUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role is for patients",
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role is for doctors",
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role_id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "523 Reyes Vista",
                            Age = 34,
                            DateOfBirth = new DateTime(2004, 5, 5, 18, 15, 29, 684, DateTimeKind.Local).AddTicks(2408),
                            Email = "Jeanne.Hudson@yahoo.com",
                            FirstName = "Terry",
                            Gender = "Female",
                            LastName = "Bartell",
                            Password = "tuaeuaua",
                            PhoneNumber = "1-572-624-9558 x777",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "80617 Hauck Gateway",
                            Age = 63,
                            DateOfBirth = new DateTime(1929, 9, 4, 7, 47, 18, 703, DateTimeKind.Local).AddTicks(8629),
                            Email = "Hildegard85@hotmail.com",
                            FirstName = "Hoyt",
                            Gender = "Male",
                            LastName = "Berge",
                            Password = "joaeeiao",
                            PhoneNumber = "1-997-766-6888 x3850",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "8943 Emiliano Oval",
                            Age = 60,
                            DateOfBirth = new DateTime(1949, 11, 6, 11, 32, 29, 957, DateTimeKind.Local).AddTicks(6163),
                            Email = "Dixie70@hotmail.com",
                            FirstName = "Stephania",
                            Gender = "Female",
                            LastName = "Monahan",
                            Password = "louoioou",
                            PhoneNumber = "873-484-9501 x83798",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Address = "7535 Flo Road",
                            Age = 67,
                            DateOfBirth = new DateTime(1949, 9, 25, 16, 25, 45, 794, DateTimeKind.Local).AddTicks(1832),
                            Email = "Randi_Nicolas@gmail.com",
                            FirstName = "Tyler",
                            Gender = "Male",
                            LastName = "Macejkovic",
                            Password = "vaeieieo",
                            PhoneNumber = "697.983.2219",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "265 Mohr Cape",
                            Age = 56,
                            DateOfBirth = new DateTime(1949, 8, 15, 17, 18, 12, 379, DateTimeKind.Local).AddTicks(5509),
                            Email = "Dameon_Robel@hotmail.com",
                            FirstName = "Reid",
                            Gender = "Male",
                            LastName = "Dare",
                            Password = "hiuioeiu",
                            PhoneNumber = "848-418-5106 x0072",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "38842 O'Keefe Expressway",
                            Age = 22,
                            DateOfBirth = new DateTime(1986, 1, 27, 17, 48, 44, 366, DateTimeKind.Local).AddTicks(1416),
                            Email = "Mireille_Walker@gmail.com",
                            FirstName = "Zoe",
                            Gender = "Male",
                            LastName = "Heaney",
                            Password = "paiiuuiu",
                            PhoneNumber = "(916) 238-9400",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            Address = "674 Araceli Garden",
                            Age = 96,
                            DateOfBirth = new DateTime(1971, 4, 7, 8, 47, 26, 6, DateTimeKind.Local).AddTicks(7837),
                            Email = "Llewellyn_Jenkins19@hotmail.com",
                            FirstName = "Hermina",
                            Gender = "Other",
                            LastName = "Corkery",
                            Password = "kiuiaaau",
                            PhoneNumber = "558-732-2413 x709",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            Address = "0594 Mohr Curve",
                            Age = 20,
                            DateOfBirth = new DateTime(1977, 2, 22, 15, 10, 11, 140, DateTimeKind.Local).AddTicks(2784),
                            Email = "Tyrique.Dooley3@yahoo.com",
                            FirstName = "Jenifer",
                            Gender = "Male",
                            LastName = "Hackett",
                            Password = "gueuaeuo",
                            PhoneNumber = "(615) 285-7098 x6235",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "425 Rico Ways",
                            Age = 65,
                            DateOfBirth = new DateTime(1974, 4, 22, 12, 17, 28, 355, DateTimeKind.Local).AddTicks(9519),
                            Email = "Damon_Batz@yahoo.com",
                            FirstName = "Leatha",
                            Gender = "Other",
                            LastName = "Beier",
                            Password = "touiauae",
                            PhoneNumber = "728-299-6688 x0249",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "27737 Brice Shores",
                            Age = 63,
                            DateOfBirth = new DateTime(1948, 9, 18, 2, 36, 41, 255, DateTimeKind.Local).AddTicks(6995),
                            Email = "Cristobal24@hotmail.com",
                            FirstName = "Cordie",
                            Gender = "Male",
                            LastName = "Hayes",
                            Password = "yooaiaeu",
                            PhoneNumber = "(546) 959-6142 x2663",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.User", b =>
                {
                    b.HasOne("Assessment_JulianFelipeForeroVilla.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
