// <auto-generated />
using System;
using Assessment_JulianFelipeForeroVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_JulianFelipeForeroVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115155358_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role is for patients",
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role is for doctors",
                            Name = "Doctor"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<int?>("role_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("role_id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "47152 Labadie Fort",
                            Age = 91,
                            DateOfBirth = new DateTime(1972, 8, 6, 15, 2, 47, 874, DateTimeKind.Local).AddTicks(8099),
                            Email = "Celine15@gmail.com",
                            FirstName = "Lera",
                            Gender = "Male",
                            LastName = "Gottlieb",
                            Password = "nieouauo",
                            PhoneNumber = "614-247-2021",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "57909 Rempel Shoals",
                            Age = 53,
                            DateOfBirth = new DateTime(1954, 2, 23, 2, 25, 1, 478, DateTimeKind.Local).AddTicks(5165),
                            Email = "Nicholaus92@hotmail.com",
                            FirstName = "Sean",
                            Gender = "Male",
                            LastName = "Murazik",
                            Password = "soeeaeao",
                            PhoneNumber = "450.706.0421",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "09524 Joelle Ridge",
                            Age = 85,
                            DateOfBirth = new DateTime(2002, 7, 8, 17, 35, 46, 862, DateTimeKind.Local).AddTicks(1055),
                            Email = "Sally8@gmail.com",
                            FirstName = "Myrtle",
                            Gender = "Female",
                            LastName = "Wyman",
                            Password = "poieaouo",
                            PhoneNumber = "(656) 873-5819",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "0785 Daron Divide",
                            Age = 71,
                            DateOfBirth = new DateTime(1989, 8, 24, 5, 45, 32, 251, DateTimeKind.Local).AddTicks(973),
                            Email = "Cara.Waters@hotmail.com",
                            FirstName = "Ramiro",
                            Gender = "Female",
                            LastName = "Kub",
                            Password = "woieooea",
                            PhoneNumber = "581-532-7648 x60036",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Address = "17609 Oscar Coves",
                            Age = 49,
                            DateOfBirth = new DateTime(1947, 1, 25, 15, 23, 45, 972, DateTimeKind.Local).AddTicks(3251),
                            Email = "Tyshawn_Lebsack@yahoo.com",
                            FirstName = "Olga",
                            Gender = "Male",
                            LastName = "Steuber",
                            Password = "fuiioauo",
                            PhoneNumber = "534.984.0426",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "1531 Prosacco Mountains",
                            Age = 99,
                            DateOfBirth = new DateTime(2002, 11, 25, 2, 20, 48, 118, DateTimeKind.Local).AddTicks(7164),
                            Email = "Jaime.Nicolas26@yahoo.com",
                            FirstName = "Finn",
                            Gender = "Female",
                            LastName = "Feeney",
                            Password = "neiieiie",
                            PhoneNumber = "616.703.8000 x5185",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "4121 Stokes Hill",
                            Age = 62,
                            DateOfBirth = new DateTime(2006, 8, 11, 7, 38, 49, 34, DateTimeKind.Local).AddTicks(8199),
                            Email = "Felipa_Quitzon32@gmail.com",
                            FirstName = "Annabel",
                            Gender = "Other",
                            LastName = "Purdy",
                            Password = "seieuaiu",
                            PhoneNumber = "954-771-1529",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            Address = "74860 Hamill Trace",
                            Age = 25,
                            DateOfBirth = new DateTime(1994, 6, 10, 14, 30, 59, 178, DateTimeKind.Local).AddTicks(4357),
                            Email = "Noemi98@yahoo.com",
                            FirstName = "Cristina",
                            Gender = "Female",
                            LastName = "Prohaska",
                            Password = "kauaoeoa",
                            PhoneNumber = "256-776-1882",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            Address = "48656 Constantin Flat",
                            Age = 38,
                            DateOfBirth = new DateTime(1979, 2, 4, 23, 3, 10, 915, DateTimeKind.Local).AddTicks(4901),
                            Email = "Narciso_Schoen55@yahoo.com",
                            FirstName = "Kenya",
                            Gender = "Female",
                            LastName = "Satterfield",
                            Password = "tieiuoee",
                            PhoneNumber = "838-485-0715 x9351",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            Address = "75073 Gregory Drive",
                            Age = 64,
                            DateOfBirth = new DateTime(1954, 8, 31, 5, 44, 18, 379, DateTimeKind.Local).AddTicks(5812),
                            Email = "Davon78@hotmail.com",
                            FirstName = "Josiah",
                            Gender = "Female",
                            LastName = "Boyer",
                            Password = "souiuuou",
                            PhoneNumber = "647-775-3608",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.User", b =>
                {
                    b.HasOne("Assessment_JulianFelipeForeroVilla.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
