// <auto-generated />
using System;
using Assessment_JulianFelipeForeroVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_JulianFelipeForeroVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115162230_CreateTableMourner")]
    partial class CreateTableMourner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Mourner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("mourners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1645 Ewell Hill",
                            Age = 85,
                            DateOfBirth = new DateTime(1992, 1, 1, 17, 31, 51, 373, DateTimeKind.Local).AddTicks(5907),
                            Email = "Buck.Klein70@hotmail.com",
                            FirstName = "Lupe",
                            Gender = "Other",
                            LastName = "Hermiston",
                            Password = "doeoiaai",
                            PhoneNumber = "(361) 474-1501 x267"
                        },
                        new
                        {
                            Id = 2,
                            Address = "4459 Kiara Walk",
                            Age = 32,
                            DateOfBirth = new DateTime(1940, 8, 25, 17, 21, 25, 81, DateTimeKind.Local).AddTicks(3377),
                            Email = "Eldridge29@hotmail.com",
                            FirstName = "Eliane",
                            Gender = "Other",
                            LastName = "Boyle",
                            Password = "veooeaoe",
                            PhoneNumber = "413.816.2343 x2720"
                        },
                        new
                        {
                            Id = 3,
                            Address = "6787 Kathlyn Meadows",
                            Age = 35,
                            DateOfBirth = new DateTime(2005, 2, 24, 19, 7, 39, 335, DateTimeKind.Local).AddTicks(5986),
                            Email = "Burdette.McKenzie76@hotmail.com",
                            FirstName = "Demario",
                            Gender = "Female",
                            LastName = "Shanahan",
                            Password = "taaaouoa",
                            PhoneNumber = "980-798-4443"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4347 Muller Parkway",
                            Age = 18,
                            DateOfBirth = new DateTime(1976, 10, 13, 0, 16, 36, 549, DateTimeKind.Local).AddTicks(9073),
                            Email = "Merle_Mohr67@gmail.com",
                            FirstName = "Margarita",
                            Gender = "Other",
                            LastName = "Stanton",
                            Password = "vaaoaeie",
                            PhoneNumber = "450-551-8694 x755"
                        },
                        new
                        {
                            Id = 5,
                            Address = "1502 Brooks Gateway",
                            Age = 54,
                            DateOfBirth = new DateTime(1974, 3, 24, 13, 45, 28, 760, DateTimeKind.Local).AddTicks(4401),
                            Email = "Aileen6@hotmail.com",
                            FirstName = "Alvina",
                            Gender = "Female",
                            LastName = "Dietrich",
                            Password = "baueiuoi",
                            PhoneNumber = "225.418.8380"
                        },
                        new
                        {
                            Id = 6,
                            Address = "624 Larue Inlet",
                            Age = 96,
                            DateOfBirth = new DateTime(1980, 11, 28, 16, 59, 43, 896, DateTimeKind.Local).AddTicks(5566),
                            Email = "Katherine_Huels@yahoo.com",
                            FirstName = "Kolby",
                            Gender = "Male",
                            LastName = "Nader",
                            Password = "faieoeae",
                            PhoneNumber = "221.656.2079 x90863"
                        },
                        new
                        {
                            Id = 7,
                            Address = "41761 Zachariah Brook",
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 5, 31, 4, 57, 48, 774, DateTimeKind.Local).AddTicks(7263),
                            Email = "Cordell16@gmail.com",
                            FirstName = "Mollie",
                            Gender = "Male",
                            LastName = "Becker",
                            Password = "qoaouooo",
                            PhoneNumber = "818.708.7437 x2453"
                        },
                        new
                        {
                            Id = 8,
                            Address = "19845 Johnson Greens",
                            Age = 22,
                            DateOfBirth = new DateTime(1980, 2, 25, 14, 14, 28, 950, DateTimeKind.Local).AddTicks(5097),
                            Email = "Opal.Beier@gmail.com",
                            FirstName = "Jarrett",
                            Gender = "Other",
                            LastName = "Deckow",
                            Password = "soeuauui",
                            PhoneNumber = "693.217.1420 x451"
                        },
                        new
                        {
                            Id = 9,
                            Address = "10124 Block Drive",
                            Age = 66,
                            DateOfBirth = new DateTime(1953, 11, 19, 20, 38, 8, 637, DateTimeKind.Local).AddTicks(3216),
                            Email = "Kayleigh.Kutch50@hotmail.com",
                            FirstName = "Ross",
                            Gender = "Female",
                            LastName = "Bosco",
                            Password = "qauueeea",
                            PhoneNumber = "(810) 788-3349 x570"
                        },
                        new
                        {
                            Id = 10,
                            Address = "58643 Borer Lights",
                            Age = 82,
                            DateOfBirth = new DateTime(1957, 8, 9, 20, 2, 45, 819, DateTimeKind.Local).AddTicks(4901),
                            Email = "Howard.Kihn@gmail.com",
                            FirstName = "Roderick",
                            Gender = "Other",
                            LastName = "Johnson",
                            Password = "cieuiaee",
                            PhoneNumber = "871-547-6164"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role is for patients",
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role is for doctors",
                            Name = "Doctor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
