// <auto-generated />
using System;
using Assessment_JulianFelipeForeroVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_JulianFelipeForeroVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115162435_SeedMourners")]
    partial class SeedMourners
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Mourner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("mourners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "6530 Brenna Lane",
                            Age = 58,
                            DateOfBirth = new DateTime(1996, 11, 14, 3, 3, 35, 915, DateTimeKind.Local).AddTicks(7017),
                            Email = "Antoinette.Bosco@yahoo.com",
                            FirstName = "Connie",
                            Gender = "Female",
                            LastName = "Bogisich",
                            Password = "puaeeiee",
                            PhoneNumber = "876.464.2089 x656"
                        },
                        new
                        {
                            Id = 2,
                            Address = "194 Medhurst Rapids",
                            Age = 57,
                            DateOfBirth = new DateTime(1985, 1, 26, 2, 10, 34, 809, DateTimeKind.Local).AddTicks(1581),
                            Email = "Nyah_Veum@gmail.com",
                            FirstName = "Orland",
                            Gender = "Male",
                            LastName = "Emmerich",
                            Password = "raeuoaoa",
                            PhoneNumber = "953.609.4984 x79419"
                        },
                        new
                        {
                            Id = 3,
                            Address = "94115 Prohaska Field",
                            Age = 31,
                            DateOfBirth = new DateTime(2000, 6, 21, 7, 39, 58, 696, DateTimeKind.Local).AddTicks(3821),
                            Email = "Stanford97@yahoo.com",
                            FirstName = "Emie",
                            Gender = "Male",
                            LastName = "Brakus",
                            Password = "biouaioa",
                            PhoneNumber = "1-876-663-2331"
                        },
                        new
                        {
                            Id = 4,
                            Address = "106 Frieda Points",
                            Age = 63,
                            DateOfBirth = new DateTime(1944, 2, 28, 14, 40, 48, 428, DateTimeKind.Local).AddTicks(8205),
                            Email = "Hadley.Schamberger25@yahoo.com",
                            FirstName = "Mafalda",
                            Gender = "Female",
                            LastName = "Sawayn",
                            Password = "peeaoaoa",
                            PhoneNumber = "1-349-929-5629 x354"
                        },
                        new
                        {
                            Id = 5,
                            Address = "697 Fisher Route",
                            Age = 84,
                            DateOfBirth = new DateTime(1979, 10, 18, 3, 34, 23, 201, DateTimeKind.Local).AddTicks(6530),
                            Email = "Catharine.Feeney81@gmail.com",
                            FirstName = "Joanie",
                            Gender = "Other",
                            LastName = "Orn",
                            Password = "loioieiu",
                            PhoneNumber = "1-307-662-7853 x925"
                        },
                        new
                        {
                            Id = 6,
                            Address = "504 Vincent Glen",
                            Age = 28,
                            DateOfBirth = new DateTime(1971, 5, 29, 13, 26, 11, 193, DateTimeKind.Local).AddTicks(9013),
                            Email = "Karlie.Romaguera84@gmail.com",
                            FirstName = "Laney",
                            Gender = "Female",
                            LastName = "Lemke",
                            Password = "qooieeii",
                            PhoneNumber = "1-637-356-6324"
                        },
                        new
                        {
                            Id = 7,
                            Address = "1857 Predovic Hill",
                            Age = 59,
                            DateOfBirth = new DateTime(1935, 12, 3, 3, 2, 7, 169, DateTimeKind.Local).AddTicks(7985),
                            Email = "Monique_Cummings95@gmail.com",
                            FirstName = "Mitchell",
                            Gender = "Other",
                            LastName = "Koss",
                            Password = "faeiueoa",
                            PhoneNumber = "(480) 392-6251 x8613"
                        },
                        new
                        {
                            Id = 8,
                            Address = "0713 Mann Freeway",
                            Age = 98,
                            DateOfBirth = new DateTime(1932, 8, 1, 10, 16, 29, 990, DateTimeKind.Local).AddTicks(9747),
                            Email = "Jamel.Swaniawski43@gmail.com",
                            FirstName = "Fletcher",
                            Gender = "Male",
                            LastName = "McCullough",
                            Password = "qiaoueae",
                            PhoneNumber = "1-200-349-2371 x464"
                        },
                        new
                        {
                            Id = 9,
                            Address = "31108 Berge Dale",
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 10, 3, 1, 51, 32, 640, DateTimeKind.Local).AddTicks(748),
                            Email = "Keyon.Kassulke4@gmail.com",
                            FirstName = "Roel",
                            Gender = "Male",
                            LastName = "Blick",
                            Password = "naaiouoo",
                            PhoneNumber = "(728) 425-2455 x6917"
                        },
                        new
                        {
                            Id = 10,
                            Address = "52268 Windler Common",
                            Age = 87,
                            DateOfBirth = new DateTime(1989, 4, 6, 22, 2, 38, 560, DateTimeKind.Local).AddTicks(6577),
                            Email = "Colten.Jakubowski@gmail.com",
                            FirstName = "Margie",
                            Gender = "Other",
                            LastName = "Ledner",
                            Password = "lueuauua",
                            PhoneNumber = "760.674.3169"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This role is for patients",
                            Name = "Patient"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This role is for doctors",
                            Name = "Doctor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
