// <auto-generated />
using System;
using Assessment_JulianFelipeForeroVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_JulianFelipeForeroVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241115175958_SeedDoctors")]
    partial class SeedDoctors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<int>("Office")
                        .HasColumnType("int")
                        .HasColumnName("office");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("specialty_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Trycia.Stark@gmail.com",
                            FirstName = "Gage",
                            Gender = "Other",
                            LastName = "Welch",
                            Office = 170,
                            Password = "kaiueoua",
                            SpecialtyId = 3,
                            Status = "Moen - Mann"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Malachi_Bechtelar50@yahoo.com",
                            FirstName = "Kristy",
                            Gender = "Female",
                            LastName = "Hand",
                            Office = 28,
                            Password = "tooiuueu",
                            SpecialtyId = 9,
                            Status = "Green - Yost"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Quentin_Blanda@gmail.com",
                            FirstName = "Viva",
                            Gender = "Other",
                            LastName = "Jerde",
                            Office = 222,
                            Password = "quueuaai",
                            SpecialtyId = 2,
                            Status = "Kozey, Carter and Fadel"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Tessie.Konopelski@hotmail.com",
                            FirstName = "Ludie",
                            Gender = "Other",
                            LastName = "Bernhard",
                            Office = 109,
                            Password = "cauiaiae",
                            SpecialtyId = 1,
                            Status = "Jacobson - Rosenbaum"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Ben27@yahoo.com",
                            FirstName = "Jazmyn",
                            Gender = "Female",
                            LastName = "Torp",
                            Office = 171,
                            Password = "jaoauiee",
                            SpecialtyId = 3,
                            Status = "Kuvalis - Koss"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Isom.Kuhlman@yahoo.com",
                            FirstName = "Tyra",
                            Gender = "Female",
                            LastName = "Stanton",
                            Office = 287,
                            Password = "sueuooae",
                            SpecialtyId = 11,
                            Status = "Leuschke, Hahn and Lindgren"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Morgan_Gleichner@yahoo.com",
                            FirstName = "Heidi",
                            Gender = "Male",
                            LastName = "Stoltenberg",
                            Office = 194,
                            Password = "ceooeeoa",
                            SpecialtyId = 11,
                            Status = "Runte, Raynor and Lesch"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Sanford20@hotmail.com",
                            FirstName = "Chaya",
                            Gender = "Male",
                            LastName = "Quigley",
                            Office = 236,
                            Password = "nueaaoii",
                            SpecialtyId = 15,
                            Status = "Reilly LLC"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Nicolas.Casper20@hotmail.com",
                            FirstName = "Grover",
                            Gender = "Other",
                            LastName = "Stroman",
                            Office = 237,
                            Password = "tiuaaaie",
                            SpecialtyId = 9,
                            Status = "Cummerata LLC"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Kamryn.Heidenreich58@yahoo.com",
                            FirstName = "Nicolette",
                            Gender = "Other",
                            LastName = "Adams",
                            Office = 161,
                            Password = "geaueoua",
                            SpecialtyId = 7,
                            Status = "Dietrich - Brown"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Mourner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("address");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nationality");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("mourners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "1912 Linwood Highway",
                            Age = 83,
                            DateOfBirth = new DateTime(1928, 8, 29, 1, 1, 38, 89, DateTimeKind.Local).AddTicks(6829),
                            Email = "Ryder.Larkin88@hotmail.com",
                            FirstName = "Moises",
                            Gender = "Other",
                            LastName = "Wisoky",
                            Password = "yuoueeae",
                            PhoneNumber = "(366) 882-7392 x252"
                        },
                        new
                        {
                            Id = 2,
                            Address = "5188 Edwardo Shore",
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 3, 4, 3, 37, 9, 504, DateTimeKind.Local).AddTicks(9919),
                            Email = "Quincy.Cole@gmail.com",
                            FirstName = "Eino",
                            Gender = "Other",
                            LastName = "Berge",
                            Password = "wiuaeuau",
                            PhoneNumber = "382.516.8130"
                        },
                        new
                        {
                            Id = 3,
                            Address = "0262 Hoppe Via",
                            Age = 50,
                            DateOfBirth = new DateTime(1940, 2, 7, 6, 3, 29, 69, DateTimeKind.Local).AddTicks(6588),
                            Email = "Nikita18@yahoo.com",
                            FirstName = "Madyson",
                            Gender = "Male",
                            LastName = "McKenzie",
                            Password = "xeouuoiu",
                            PhoneNumber = "841.304.4682 x4503"
                        },
                        new
                        {
                            Id = 4,
                            Address = "82864 Graham Glen",
                            Age = 81,
                            DateOfBirth = new DateTime(1968, 8, 13, 21, 29, 49, 905, DateTimeKind.Local).AddTicks(6795),
                            Email = "Eudora_Kling@hotmail.com",
                            FirstName = "Seth",
                            Gender = "Other",
                            LastName = "Emard",
                            Password = "seaiuiuo",
                            PhoneNumber = "1-759-768-2157"
                        },
                        new
                        {
                            Id = 5,
                            Address = "95215 Brown Lane",
                            Age = 72,
                            DateOfBirth = new DateTime(1975, 4, 6, 7, 42, 11, 645, DateTimeKind.Local).AddTicks(4728),
                            Email = "Hubert20@gmail.com",
                            FirstName = "Floyd",
                            Gender = "Male",
                            LastName = "Runolfsdottir",
                            Password = "geiauaau",
                            PhoneNumber = "273.537.0041"
                        },
                        new
                        {
                            Id = 6,
                            Address = "166 Antoinette Branch",
                            Age = 24,
                            DateOfBirth = new DateTime(1978, 2, 3, 20, 18, 32, 735, DateTimeKind.Local).AddTicks(2312),
                            Email = "Alison_Stoltenberg9@yahoo.com",
                            FirstName = "Reina",
                            Gender = "Male",
                            LastName = "Nikolaus",
                            Password = "jueaiiei",
                            PhoneNumber = "944.762.9623"
                        },
                        new
                        {
                            Id = 7,
                            Address = "42893 Ona Loaf",
                            Age = 55,
                            DateOfBirth = new DateTime(1929, 11, 20, 9, 49, 55, 789, DateTimeKind.Local).AddTicks(9251),
                            Email = "Clint67@hotmail.com",
                            FirstName = "Sylvia",
                            Gender = "Female",
                            LastName = "Hermiston",
                            Password = "suaieiea",
                            PhoneNumber = "(835) 816-2398 x781"
                        },
                        new
                        {
                            Id = 8,
                            Address = "14302 Pollich Inlet",
                            Age = 32,
                            DateOfBirth = new DateTime(1933, 5, 14, 23, 50, 2, 192, DateTimeKind.Local).AddTicks(7591),
                            Email = "Roberta17@gmail.com",
                            FirstName = "Philip",
                            Gender = "Other",
                            LastName = "Conroy",
                            Password = "roaaaoie",
                            PhoneNumber = "590.631.8052 x078"
                        },
                        new
                        {
                            Id = 9,
                            Address = "08835 Stella Stream",
                            Age = 49,
                            DateOfBirth = new DateTime(1985, 2, 28, 21, 17, 49, 231, DateTimeKind.Local).AddTicks(5443),
                            Email = "Alfredo_Olson94@yahoo.com",
                            FirstName = "Brain",
                            Gender = "Male",
                            LastName = "Schimmel",
                            Password = "yiuaoiae",
                            PhoneNumber = "1-796-234-0346 x685"
                        },
                        new
                        {
                            Id = 10,
                            Address = "28055 Kuhn Creek",
                            Age = 48,
                            DateOfBirth = new DateTime(1975, 2, 26, 12, 32, 31, 249, DateTimeKind.Local).AddTicks(6584),
                            Email = "Gregoria_Koelpin@hotmail.com",
                            FirstName = "Ena",
                            Gender = "Male",
                            LastName = "Jacobi",
                            Password = "wuaoeaai",
                            PhoneNumber = "962.684.3215"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Specialty focused on heart health and diseases",
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Specialty dealing with disorders of the nervous system",
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Specialty for children's health and diseases",
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Specialty for skin, hair, and nail conditions",
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Specialty for the musculoskeletal system",
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Specialty for cancer diagnosis and treatment",
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Specialty for mental health disorders and treatments",
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Specialty for female reproductive health",
                            Name = "Gynecology"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Specialty for eye health and vision disorders",
                            Name = "Ophthalmology"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Specialty focused on anesthesia and perioperative care",
                            Name = "Anesthesiology"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Specialty for hormonal disorders and diseases",
                            Name = "Endocrinology"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Specialty for digestive system disorders",
                            Name = "Gastroenterology"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Specialty for urinary tract and male reproductive system",
                            Name = "Urology"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Specialty for lung and respiratory system disorders",
                            Name = "Pulmonology"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Specialty for autoimmune and musculoskeletal diseases",
                            Name = "Rheumatology"
                        });
                });

            modelBuilder.Entity("Assessment_JulianFelipeForeroVilla.Models.Doctor", b =>
                {
                    b.HasOne("Assessment_JulianFelipeForeroVilla.Models.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialty");
                });
#pragma warning restore 612, 618
        }
    }
}
